name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    name: Gradle Setup
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - uses: gradle/actions/wrapper-validation@v4
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Gradle Information
        run: ./gradlew project tasks dependencies

  build:
    strategy:
      fail-fast: false
      matrix:
        java-version: [17, 21]

    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 20

    name: Gradle Build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Gradle Build
        run: ./gradlew clean assemble

  test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20

    name: Gradle Test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Gradle Test
        run: ./gradlew check

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy Dokka
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Build Dokka
        run: ./gradlew clean dokkaHtml
      - name: Deploy Dokka
        run: bash dokka.sh ${GITHUB_SHA::7}

  publish:
    runs-on: macos-latest
    needs: build
    name: Publish to Repository
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1
      - name: Publish to Repository
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew clean assemble publish -Psnapshot=true
